language: java
jdk:
- oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
after_success:
- "./gradlew bintrayUpload"
deploy:
  provider: releases
  api_key:
    secure: "${GITHUB_API_KEY_SECURE}"
  file_glob: true
  file: build/libs/*.jar
  on:
    repo: VcSaJen/MyCustomVeh
    tags: true
notifications:
  email:
    on_success: never